apiVersion: v1
kind: Service
metadata:
  name: "clustermesh-apiserver"
  #annotations:
  #  cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
  - port: 2379
    name: api
  type: CluserIP
  selector:
    name: "clustermesh-apiserver"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "clustermesh-apiserver"
  labels:
    name: "clustermesh-apiserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "clustermesh-apiserver"
  template:
    metadata:
      labels:
        name: "clustermesh-apiserver"
    spec:
      serviceAccount: clustermesh-apiserver
      containers:
      - name: "etcd"
        image: "quay.io/coreos/etcd:v3.4.7"
        env:
        - name: ETCDCTL_API
          value: "3"
        - name: HOSTNAME_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
          - "/usr/local/bin/etcd"
        args:
          - --name=clustermesh-apiserver
          - --listen-client-urls=http://0.0.0.0:2379
          - --advertise-client-urls=http://$(HOSTNAME_IP):2379
          - --initial-cluster-token=clustermesh-apiserver
          - --initial-cluster-state=new
          - --auto-compaction-retention=1
      - name: "apiserver"
        image: "cilium/clustermesh-apiserver:latest"
        command:
          - "/usr/bin/clustermesh-apiserver"
        args:
          - --mock-file=/mock.json
          - --cluster-name=$(CLUSTER_NAME)
          - --cluster-id=$(CLUSTER_ID)
        env:
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              key: cluster-name
              name: cilium-config
        - name: CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: cluster-id
              name: cilium-config
